language: r

cache: packages

install:
    - Rscript -e 'install.packages(c("devtools", "testthat", "huge", "igraph", "covr"))'
    - Rscript -e 'devtools::install_github("cdgreenidge/brcbase", ref = "kevin")'

after_success:
  - Rscript -e 'library(covr); codecov()'

warnings_are_errors: true
